# © this module created by @pegasusXteam

GBUN = (
    "Beware! This Bot-Admeme Can Gbun You Right Off The Map.",
    "I Guess You've Forgot Spelling Of GBAN Maybe...?",
    "Don't Misuse Your Powers...",
    "Nah, He Looks Innocent...",
)


GBAM = "<b>Beginning Of Global Bam For {user2}</b>  \n \nChat Id : <code>{chatid}</code> \nReason : <i>{reason}</i> \nGBammed By {user1}"

# These words for just for fun don't mind it
GBAM_REASON = (
    "a bitch",
    "gay to gay",
    "no 1 noob",
    "fucker",
    "mother ticker",
    "One punch a gay",
    "fuck of topic",
    "no respect",
    "chuthiya bhaiya",
    "Kundu Pusanika",
    "Manda Paila",
    "Savu la Nee Poi savu",
    "Modi tu poda",
    "Mundam",
    "Arivuktha mudnam",
    "Korangu",
    "Korean gays",
    "Potta",
    "Mairu",
)

DECIDE = ("Yes.", "IDK.", "Maybe.", "No.")

TRUTH = (
    "Do you pick your nose?",
    "Do you sing in the shower? ",
    "Do you ever talk to yourself in the mirror? ",
    "Have you ghosted someone?",
    "Have you ever walked in on your parents doing 'it'?",
    "Who was the last person you liked the most? Why?",
    "Have you ever been suspended from school?",
    "If you had to choose between going naked or having your thoughts appear in thought bubbles above your head for everyone to read, which would you choose?",
    "What’s the one thing you’re afraid to lose?",
    "Do you like someone as of the moment?",
    "One thing about your best friend you are jealous of?",
    "Would you cheat on your boyfriend for a rich guy?",
    "What is your biggest turn on?",
    "When’s the last time you lied to your parents and why?",
    "Describe your ideal partner.",
    "What’s the scariest thing you’ve ever done?",
    "Have you ever picked your nose and eaten it?",
    "When’s the last time you lied to your parents and why?",
    "Have you ever lied about your age to participate in a contest?",
    "Have you ever been caught checking someone out?",
    "Do you talk in your sleep?",
    "Do you think you'll marry your current girlfriend/boyfriend?",
    "Would you trade your sibling in for a million dollars?",
    "Would You Slap Your Bestfriend For A Million Dollars?",
    "Have you ever had a crush on a teacher?",
    "Have you ever smoked?",
    "Have you ever tried drugs?",
    "What about alcohol?",
    "Are you still a virgin?",
    "describe your perfect partner.",
    "If you could make $1 million, would you drop out of school?",
    "What is your worst habit?",
    "How many people have you kissed?",
    "Describe what your crush looks like.",
    "If your friend and your boyfriend were both dying in front of you, who would try to save first?",
    "Do you think your friend's (Boyfriend/Girlfriend) is hot?",
    "If someone asked you what your best friend is like, how would you describe her/him?",
    "What do you think about him/her now?",
    "Kya Apke Toothpaste Me Namak He?",
    "Rasode Me Kon Tha?",
    "If you had to trade your friend in for the celebrity crush of your dreams, which friend would you choose?",
    "Would you share a toothbrush with your best friend?",
    "Who's hotter? You or your friend?",
    "Who Is Stupid?\n (A. Your Friend\n  (B. You",
    "Have you ever told a lie about your best friend to make yourself look better?",
    "What's one food that you will never order at a restaurant?",
    "What's one thing you would never eat on a first date?",
    "How long have you gone without brushing your teeth?",
    "How long have you gone without a shower?",
)

DARE = (
    "Show the most embarrassing photo on your phone",
    "Show the last five people you texted and what the messages said",
    "Let the rest of the group DM someone from your Instagram account",
    "Eat a raw piece of garlic",
    "Do 100 squats",
    "Keep three ice cubes in your mouth until they melt",
    "Say something dirty to the person on your leftYou've got company!",
    "Give a foot massage to the person on your right",
    "Put 10 different available liquids into a cup and drink it",
    "*Yell out the first word that comes to your mind",
    "Give a lap dance to someone of your choice",
    "Remove four items of clothing",
    "Like the first 15 posts on your Facebook newsfeed",
    "Eat a spoonful of mustard",
    "Keep your eyes closed until it's your go again",
    "Send a sext to the last person in your phonebook",
    "Show off your orgasm face",
    "Seductively eat a banana",
    "Empty out your wallet/purse and show everyone what's inside",
    "Do your best sexy crawl",
    "Pretend to be the person to your right for 10 minutes",
    "Eat a snack without using your hands",
    "Say two honest things about everyone else in the group",
    "Twerk for a minute",
    "Try and make the group laugh as quickly as possible",
    "Try to put your whole fist in your mouth",
    "Tell everyone an embarrassing story about yourself",
    "Try to lick your elbow",
    "Post the oldest selfie on your phone on Instagram Stories",
    "Tell the saddest story you know",
    "Howl like a wolf for two minutes",
    "Dance without music for two minutes",
    "Pole dance with an imaginary pole",
    "Let someone else tickle you and try not to laugh",
    "Put as many snacks into your mouth at once as you can",
    "Send your most recent selfie.",
    "Send your ugliest selfie.",
    "Send a screenshot of your facebook search history",
    "Send a screenshot of your gallery.",
    "Send a screenshot of your messenger inbox",
    "Tell something very intimate.",
    "Send a screenshot of your twitter inbox",
    "Send a screenshot of your homescreen.",
    "Send a cover of your favorite song. 🎤",
    "Do a lyric prank on someone and send proof.",
    "Confess to your current crush. ❤️",
    "Declare who is your true love.",
    "Send a screenshot of your gallery.",
    "Set your crush’s picture as your dp.",
    )




    
    
