# © this module created by @pegasusXteam

TAMIL_MEME = (
"https://telegra.ph/file/5f414b8f0a4b4f316f894.jpg",
"https://telegra.ph/file/73996272d459c6ea16bf7.jpg",
"https://telegra.ph/file/941cde9db0b26d69703f4.jpg",
"https://telegra.ph/file/7ed6f4224d4acd08173c.jpg",
"https://telegra.ph/file/8623d5607d975e148a0cf.jpg",
"https://telegra.ph/file/a10b527b2a0f5e382b2fc.jpg",
"https://telegra.ph/file/90f5114486ff5f5fd8ea2.jpg",
"https://telegra.ph/file/762f3a13bc5e1fbdbd2b3.jpg",
"https://telegra.ph/file/87091f2dd1d010ccbadd2.jpg",
"https://telegra.ph/file/95d2d5698519544f686ec.jpg",
"https://telegra.ph/file/936d8251e3eda4c1662c4.jpg",
"https://telegra.ph/file/b73c93f2a1ae67061f9a6.jpg",
"https://telegra.ph/file/557def50ee49ec240b2c4.jpg",
"https://telegra.ph/file/2f410d8ecfe3dc925aa2c.jpg",
"https://telegra.ph/file/238ebb7d45a834405af52.jpg",
"https://telegra.ph/file/0de71fbe0519bb0c19b99.jpg",
"https://telegra.ph/file/6b85aa5aa7850e179f688.jpg",
"https://telegra.ph/file/18382ea967fbe7f581017.jpg",
"https://telegra.ph/file/107ce84d0479aafbc589f.jpg",
"https://telegra.ph/file/809079907a93fffe8b1e2.jpg",
"https://telegra.ph/file/0f5cf6e56c624c579eebc.jpg",
"https://telegra.ph/file/2956eb1cdd25c767076c4.jpg",
"https://telegra.ph/file/be1dcb843810d3b8b1bec.jpg",
"https://telegra.ph/file/b6f1a68d296e5280da321.jpg",
"https://telegra.ph/file/fbde8b6e6cbd5a9ac050f.jpg",
"https://telegra.ph/file/af046ce053eed7c01d117.jpg",
"https://telegra.ph/file/1cdb4663acd35b2fa3f65.jpg",
"https://telegra.ph/file/95f6f492fefb413124eb3.jpg",
"https://telegra.ph/file/35bd93d90181c3fa5a875.jpg",
"https://telegra.ph/file/e3a78917d3274115e4f8c.jpg",
"https://telegra.ph/file/651662a759e635077d573.jpg",
"https://telegra.ph/file/2f60ff5e98bfe1b8d13fe.jpg",
"https://telegra.ph/file/741044f3fbd1d1e3acf8d.jpg",
"https://telegra.ph/file/cfd17959b1b5bb2421be0.jpg",
"https://telegra.ph/file/802a84f102f7d237e298c.jpg",
"https://telegra.ph/file/0c2c8d9da6ea6de6d9503.jpg",
"https://telegra.ph/file/4349482d666a19378209d.jpg",
"https://telegra.ph/file/266b903a859480d301e53.jpg",
"https://telegra.ph/file/c453e3942b1f6616f40cf.jpg",
"https://telegra.ph/file/530f06e37ef4ef9d9ec68.jpg",
"https://telegra.ph/file/581b84f9ebf7b1f0c73b0.jpg",
"https://telegra.ph/file/310183b8da7b9d436619d.jpg",
"https://telegra.ph/file/c5788b7bd27771cc7cb49.jpg",
"https://telegra.ph/file/32b7bcc8fcfad1994e3d4.jpg",
"https://telegra.ph/file/dcf53740a7510f44d9a5b.jpg",
"https://telegra.ph/file/d5dfef127f805cd4341f3.jpg",
"https://telegra.ph/file/77bef07d4be70dd257fc1.jpg",
"https://telegra.ph/file/c36fe38a23512b2f6df6a.jpg",
"https://telegra.ph/file/028751fd9b8750e9891f9.jpg",
"https://telegra.ph/file/cc50ecbbbdc28ac9b2228.jpg",
"https://telegra.ph/file/142a61347f2f4fbd258c9.jpg",
"https://telegra.ph/file/c7040297d2487f1364230.jpg",
"https://telegra.ph/file/f77a80db0e08eee179c43.jpg",
"https://telegra.ph/file/97a15113108f3ecd93496.jpg",
"https://telegra.ph/file/290a1f7a9147bf01e3b67.jpg",
"https://telegra.ph/file/0a493a694626a4deee936.jpg",
"https://telegra.ph/file/10ea2d1f709632e8b5316.jpg", )

GBUN = (
    "Beware! This Bot-Admeme Can Gbun You Right Off The Map.",
    "I Guess You've Forgot Spelling Of GBAN Maybe...?",
    "Don't Misuse Your Powers...",
    "Nah, He Looks Innocent...",
)


GBAM = "<b>Beginning Of Global Bam For {user2}</b>  \n \nChat Id : <code>{chatid}</code> \nReason : <i>{reason}</i> \nGBammed By {user1}"

# These words for just for fun don't mind it
GBAM_REASON = (
    "a bitch",
    "gay to gay",
    "no 1 noob",
    "fucker",
    "mother ticker",
    "One punch a gay",
    "fuck of topic",
    "no respect",
    "chuthiya bhaiya",
    "mother likely chuthiya",
    "gay being gay",
    "using gay pack trying become a gay",
    "big dick more than sucks a bots",
    "see rules mother tickers",
    "idk. wtf he is mom sai",
    "fucking with gay bots",
    "Korean gays",
    "buying a gays",
    "mater girls",
)

DECIDE = ("Yes.", "NoU.", "Maybe.", "No.")
    
WISH = ( 
    "your Wish Possible to 25%😟*",
    "your Wish Possible to 50%🤔*",
    "your Wish Possible to 75%😉*",
    "your Wish Possible to 100%😍*" )

ABUSE_STRINGS = (
    "Fuck off",
    "Stfu go fuck yourself",
    "Ur mum gey",
    "Ur dad lesbo",
    "Bsdk",
    "Nigga",
    "Ur granny tranny",
    "you noob",
    "Relax your Rear,ders nothing to fear,The Rape train is finally here",
    "Stfu bc",
    "Stfu and Gtfo U nub",
    "GTFO bsdk",
    "CUnt",
    " Gay is here",
    "Ur dad gey bc ",
)

TRUTH = (
    "Do you pick your nose?",
    "Do you sing in the shower? ",
    "Do you ever talk to yourself in the mirror? ",
    "Have you ghosted someone?",
    "Have you ever walked in on your parents doing 'it'?",
    "Who was the last person you liked the most? Why?",
    "Have you ever been suspended from school?",
    "If you had to choose between going naked or having your thoughts appear in thought bubbles above your head for everyone to read, which would you choose?",
    "What’s the one thing you’re afraid to lose?",
    "Do you like someone as of the moment?",
    "One thing about your best friend you are jealous of?",
    "Would you cheat on your boyfriend for a rich guy?",
    "What is your biggest turn on?",
    "When’s the last time you lied to your parents and why?",
    "Describe your ideal partner.",
    "What’s the scariest thing you’ve ever done?",
    "Have you ever picked your nose and eaten it?",
    "When’s the last time you lied to your parents and why?",
    "Have you ever lied about your age to participate in a contest?",
    "Have you ever been caught checking someone out?",
    "Do you talk in your sleep?",
    "Do you think you'll marry your current girlfriend/boyfriend?",
    "Would you trade your sibling in for a million dollars?",
    "Would You Slap Your Bestfriend For A Million Dollars?",
    "Have you ever had a crush on a teacher?",
    "Have you ever smoked?",
    "Have you ever tried drugs?",
    "What about alcohol?",
    "Are you still a virgin?",
    "describe your perfect partner.",
    "If you could make $1 million, would you drop out of school?",
    "What is your worst habit?",
    "How many people have you kissed?",
    "Describe what your crush looks like.",
    "If your friend and your boyfriend were both dying in front of you, who would try to save first?",
    "Do you think your friend's (Boyfriend/Girlfriend) is hot?",
    "If someone asked you what your best friend is like, how would you describe her/him?",
    "What do you think about him/her now?",
    "Kya Apke Toothpaste Me Namak He?",
    "Rasode Me Kon Tha?",
    "If you had to trade your friend in for the celebrity crush of your dreams, which friend would you choose?",
    "Would you share a toothbrush with your best friend?",
    "Who's hotter? You or your friend?",
    "Who Is Stupid?\n (A. Your Friend\n  (B. You",
    "Have you ever told a lie about your best friend to make yourself look better?",
    "What's one food that you will never order at a restaurant?",
    "What's one thing you would never eat on a first date?",
    "How long have you gone without brushing your teeth?",
    "How long have you gone without a shower?",
)

DARE = (
    "Show the most embarrassing photo on your phone",
    "Show the last five people you texted and what the messages said",
    "Let the rest of the group DM someone from your Instagram account",
    "Eat a raw piece of garlic",
    "Do 100 squats",
    "Keep three ice cubes in your mouth until they melt",
    "Say something dirty to the person on your leftYou've got company!",
    "Give a foot massage to the person on your right",
    "Put 10 different available liquids into a cup and drink it",
    "*Yell out the first word that comes to your mind",
    "Give a lap dance to someone of your choice",
    "Remove four items of clothing",
    "Like the first 15 posts on your Facebook newsfeed",
    "Eat a spoonful of mustard",
    "Keep your eyes closed until it's your go again",
    "Send a sext to the last person in your phonebook",
    "Show off your orgasm face",
    "Seductively eat a banana",
    "Empty out your wallet/purse and show everyone what's inside",
    "Do your best sexy crawl",
    "Pretend to be the person to your right for 10 minutes",
    "Eat a snack without using your hands",
    "Say two honest things about everyone else in the group",
    "Twerk for a minute",
    "Try and make the group laugh as quickly as possible",
    "Try to put your whole fist in your mouth",
    "Tell everyone an embarrassing story about yourself",
    "Try to lick your elbow",
    "Post the oldest selfie on your phone on Instagram Stories",
    "Tell the saddest story you know",
    "Howl like a wolf for two minutes",
    "Dance without music for two minutes",
    "Pole dance with an imaginary pole",
    "Let someone else tickle you and try not to laugh",
    "Put as many snacks into your mouth at once as you can",
    "Send your most recent selfie.",
    "Send your ugliest selfie.",
    "Send a screenshot of your facebook search history",
    "Send a screenshot of your gallery.",
    "Send a screenshot of your messenger inbox",
    "Tell something very intimate.",
    "Send a screenshot of your twitter inbox",
    "Send a screenshot of your homescreen.",
    "Send a cover of your favorite song. 🎤",
    "Do a lyric prank on someone and send proof.",
    "Confess to your current crush. ❤️",
    "Declare who is your true love.",
    "Send a screenshot of your gallery.",
    "Set your crush’s picture as your dp.",
    )

PAT_TEMPLATES = (
    "{user1} pats {user2} on the head.",
    "*gently rubs {user2}'s head*.",
    "*{user1} mofumofus {user2}'s head*",
    "*{user1} messes up {user2}'s head*",
    "*{user1} intensly rubs {user2}'s head*",
    "*{user2}'s waifu pats their head*",
    "*{user2}'s got free headpats*",
    "No pats for {user2}!",
    
)

PAT_GIFS = (
    "CgACAgQAAxkBAALRX19Xs7tBdOH1gQwS_rglVRkTbgVYAAKEAgACmQn9UWlyGa_xy9_aGwQ",
    "CgACAgEAAxkBAALRYF9Xs8EnhsDfDpld3ILoqTbzDmwxAAJFAAOJxjlHECanwn69E5QbBA", 
    "CgACAgQAAxkBAAO5X7olTkYuRTw1AV__6mFehORkP4QAAiMCAAI3KIxSjBqOTuo4xf0eBA", 
    "CgACAgQAAxkBAAO6X7olTklDbgs9nr5bNbM9xy0uunUAAmACAAL1G4xSKOH5wmDvxy4eBA", 
    "CgACAgQAAxkBAAIViWDBew94TiaL_c9HyX0xpUY8wFy2AAJKAgACMU80Urc2Hvh_WMDeHwQ",
    "CgACAgQAAxkBAAO7X7olTq_mAur7bsieTD5QnyQ06rUAAlwCAAINjoRSWyAJKJ9n2moeBA") 

PAT_STICKERS = (
    "CAACAgQAAxkBAALRWV9Xs4HH0XaXfhZe-jWaZoXfs-IsAAJYAwACdDgSEHYOt4KvL02oGwQ",
    "CAACAgQAAxkBAALRXF9Xs6XmIeDbnoL1wiDky0TdX-CvAAKKAQAC1TMzC9A3CtiT2rqVGwQ", 
    "CAACAgQAAxkBAAPCX7ol0GGF-58u9AfabFk_16ehVXEAArUAA9UzMwuz7SpKK9TonB4E",
    "CAACAgQAAxkBAAPDX7ol2ixI5WdJ48h8rQYbc__6KisAAt8AA9UzMwusEnTVQ5yoAh4E", 
    "CAACAgQAAxkBAAPEX7ol55uzT-EkbHOkA-_94MiMcBgAAvAAA9UzMws7KHpoG8wBjh4E") 

SFW_STRINGS = (
    "Owww ... Such a stupid idiot.",
    "Don't drink and type.",
    "I think you should go home or better a mental asylum.",
    "Command not found. Just like your brain.",
    "Do you realize you are making a fool of yourself? Apparently not.",
    "You can type better than that.",
    "Bot rule 544 section 9 prevents me from replying to stupid humans like you.",
    "Sorry, we do not sell brains.",
    "Believe me you are not normal.",
    "I bet your brain feels as good as new, seeing that you never use it.",
    "If I wanted to kill myself I'd climb your ego and jump to your IQ.",
    "Zombies eat brains... you're safe.",
    "You didn't evolve from apes, they evolved from you.",
    "Come back and talk to me when your I.Q. exceeds your age.",
    "I'm not saying you're stupid, I'm just saying you've got bad luck when it comes to thinking.",
    "What language are you speaking? Cause it sounds like bullshit.",
    "Stupidity is not a crime so you are free to go.",
    "You are proof that evolution CAN go in reverse.",
    "I would ask you how old you are but I know you can't count that high.",
    "As an outsider, what do you think of the human race?",
    "Brains aren't everything. In your case they're nothing.",
    "Ordinarily people live and learn. You just live.",
    "I don't know what makes you so stupid, but it really works.",
    "Keep talking, someday you'll say something intelligent! (I doubt it though)",
    "Shock me, say something intelligent.",
    "Your IQ's lower than your shoe size.",
    "Alas! Your neurotransmitters are no more working.",
    "Are you crazy you fool.",
    "Everyone has the right to be stupid but you are abusing the privilege.",
    "I'm sorry I hurt your feelings when I called you stupid. I thought you already knew that.",
    "You should try tasting cyanide.",
    "Your enzymes are meant to digest rat poison.",
    "You should try sleeping forever.",
    "Pick up a gun and shoot yourself.",
    "You could make a world record by jumping from a plane without parachute.",
    "Stop talking BS and jump in front of a running bullet train.",
    "Try bathing with Hydrochloric Acid instead of water.",
    "Try this: if you hold your breath underwater for an hour, you can then hold it forever.",
    "Go Green! Stop inhaling Oxygen.",
    "God was searching for you. You should leave to meet him.",
    "give your 100%. Now, go donate blood.",
    "Try jumping from a hundred story building but you can do it only once.",
    "You should donate your brain seeing that you never used it.",
    "Volunteer for target in an firing range.",
    "Head shots are fun. Get yourself one.",
    "You should try swimming with great white sharks.",
    "You should paint yourself red and run in a bull marathon.",
    "You can stay underwater for the rest of your life without coming back up.",
    "How about you stop breathing for like 1 day? That'll be great.",
    "Try provoking a tiger while you both are in a cage.",
    "Have you tried shooting yourself as high as 100m using a canon.",
    "You should try holding TNT in your mouth and igniting it.",
    "Try playing catch and throw with RDX its fun.",
    "I heard phogine is poisonous but i guess you wont mind inhaling it for fun.",
    "Launch yourself into outer space while forgetting oxygen on Earth.",
    "You should try playing snake and ladders, with real snakes and no ladders.",
    "Dance naked on a couple of HT wires.",
    "Active Volcano is the best swimming pool for you.",
    "You should try hot bath in a volcano.",
    "Try to spend one day in a coffin and it will be yours forever.",
    "Hit Uranium with a slow moving neutron in your presence. It will be a worthwhile experience.",
    "You can be the first person to step on sun. Have a try.",
)
    
  
REPO = "https://Github.com/Ctzfamily/VegetaRobot"

  
  
    
